sudo: required
services:
  - docker

before_install: 
  - docker build -t udaykhambadkone/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run udaykhambadkone/react-test npm test -- --coverage

after_success:
  docker build -t udaykhambadkone/multi-client ./client
  docker build -t udaykhambadkone/multi-nginx ./nginx
  docker build -t udaykhambadkone/multi-server ./server
  docker build -t udaykhambadkone/multi-worker ./worker
  # login to docker cli
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take these images and push to Docker hub
  docker push udaykhambadkone/multi-client
  docker push udaykhambadkone/multi-nginx
  docker push udaykhambadkone/multi-server
  docker push udaykhambadkone/multi-worker
  