sudo: required
services:
  - docker

before_install: 
  - docker build -t udaykhambadkone/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run udaykhambadkone/react-test npm run test -- --coverage

after_success:
  - docker build -t udaykhambadkone/multi-client ./client
  - docker build -t udaykhambadkone/multi-nginx ./nginx
  - docker build -t udaykhambadkone/multi-server ./server
  - docker build -t udaykhambadkone/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take these images and push to Docker hub
  - docker push udaykhambadkone/multi-client
  - docker push udaykhambadkone/multi-nginx
  - docker push udaykhambadkone/multi-server
  - docker push udaykhambadkone/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-656001219978
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY